# Generated by Django 6.0.2 on 2026-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(default=1, verbose_name='Jornada'),
        ),
    ]
