# Generated by Django 6.0.2 on 2026-02-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('LEAGUE', 'Fase Liga'), ('PLAYOFF', 'Play-Off'), ('QUARTERS', 'Cuartos de Final'), ('SEMIS', 'Semifinal'), ('FINAL', 'Final')], default='LEAGUE', max_length=20, verbose_name='Fase'),
        ),
        migrations.CreateModel(
            name='KnockoutTie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('LEAGUE', 'Fase Liga'), ('PLAYOFF', 'Play-Off'), ('QUARTERS', 'Cuartos de Final'), ('SEMIS', 'Semifinal'), ('FINAL', 'Final')], max_length=20, verbose_name='Fase Eliminatoria')),
                ('match_1_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tie_leg_1', to='tournament.match')),
                ('match_2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tie_leg_2', to='tournament.match')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties_as_team1', to='tournament.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties_as_team2', to='tournament.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_ties', to='tournament.team')),
            ],
        ),
    ]
